# Generated by Django 5.1.1 on 2024-10-04 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_bookinstance_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_view_borrowed', 'view borrowed'), ('staff_level', 'set_staff_level'))},
        ),
    ]
